<h1>**NumPy**<h1>




In [ ]:
import numpy

In [ ]:
# initially lets import numpy
import numpy as np

In [ ]:
print(np.__version__)

1.25.2


**Creation of Arrays**

In [ ]:
my_list=[1,2,3,4]
arr=np.array(my_list)  #list gets converted to an array
print(type(arr))

<class 'numpy.ndarray'>


In [ ]:
print(arr)

[1 2 3 4]


In [ ]:
arr.size

4

In [ ]:
# chechking the dimensions with .ndim
print(arr.ndim)

1


In [ ]:
# 2D Array
my_list1=[1,22,3,14,15]
my_list2=[1,22,3,14,15]
arr1=np.array([my_list1,my_list2])
print(arr1)

my_list=[[1,2,3,4],[4,5,6,7]]
arr=np.array(my_list)
print(arr)
print("no .of dimensions:",arr.ndim)

[[ 1 22  3 14 15]
 [ 1 22  3 14 15]]
[[1 2 3 4]
 [4 5 6 7]]
no .of dimensions: 2


In [ ]:
# 3D array
arr3=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr3,"the dimensions:",arr3.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]] the dimensions: 3


In [ ]:
# boolean array
numpy_boolean_array = [[True, False], [True, True], [False, True]]

# float array
numpy_float_array = [1.9, 5.4, 8.8, 3.6, 3.2]

In [ ]:
# shape specifies how many rows and columns are there, check the shape of an array
arr.shape

(4,)

In [ ]:
my_list1=[1,2,3,4,5]
my_list2=[1,2,3,4,5]
#my_list3=[1,2,3,4,5]
arr=np.array([my_list1,my_list2,my_list3])

In [ ]:
print(arr)

[[ 1  2  3  4 50]
 [ 1  2  3  4 50]
 [ 1  2  3  4 50]]


In [ ]:
# Creating multi dimensional array
arr_nd=np.array([1,2,3,4],ndmin=10)
print(arr_nd)
print(arr_nd.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


In [ ]:
arr.shape

(3, 5)

In [ ]:
# .reshape: reshapes the array, containing the same data with new shape, numer of elements should be equal
arr.reshape(5,3)


array([[ 1,  2,  3],
       [ 4, 50,  1],
       [ 2,  3,  4],
       [50,  1,  2],
       [ 3,  4, 50]])

In [ ]:
# flatten
print(arr)
print(arr.flatten())

[[1 2 3 4]
 [4 5 6 7]]
[1 2 3 4 4 5 6 7]


In [ ]:

a = np.array([1, 2, 3, 4, 5, 6])
a.shape
print(a)

[1 2 3 4 5 6]


In [ ]:
# 1d to 2d
a2 = a[np.newaxis,: ]
a2.shape

(1, 6)

In [ ]:
print(a2)

[[1 2 3 4 5 6]]


<h2>Data Types</h2>
i - integer,
b - boolean,
u - unsigned integer,
f - float,
c - complex float,
m - timedelta,
M - datetime,
O - object,
S - string,
U - unicode string,
V - fixed chunk of memory for other type ( void )

In [ ]:
x = np.array([1, 2])   # Let numpy choose the datatype
print(x.dtype)

int64


In [ ]:
x=np.array([1.1,1.1,1.2,1.3])
print(x.dtype)

float64


In [ ]:
x = np.array([1, 2], dtype=np.int64)   # Force a particular datatype
print(x.dtype)

int64


In [ ]:
np.array(['1.32', '5.78', '175.55']).dtype

dtype('<U6')

In [ ]:
arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


In [ ]:
d = np.arange(1, 5, dtype=np.complex64)
print(d.dtype, d)

complex64 [1.+0.j 2.+0.j 3.+0.j 4.+0.j]


In [ ]:
# type conersion
boolean_array = np.array([[True, False], [False, False]])
print(boolean_array.dtype)
newarr=boolean_array.astype(np.int32)
print(newarr.dtype)


bool
int32


<h1>** Indexing**<h1>

In [ ]:
# accessing the array elements
arr= np.array([1,2,3,4,5])

In [ ]:
arr[3]

4

In [ ]:
my_list1=[1,2,3,4,5]
my_list2=[6,7,8,9,10]
my_list3=[11,12,13,14,15]
arr=np.array([my_list1,my_list2,my_list3])


In [ ]:
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [ ]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [ ]:
arr[:,:]  # retrives all the row and the column indexes

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [ ]:
arr[1:3,0:2]

array([[ 6,  7],
       [11, 12]])

In [ ]:
arr[0:2,0:2]

array([[1, 2],
       [6, 7]])

In [ ]:
arr[1:2,0:1]

array([[6]])

In [ ]:
arr[2:,3:5]

array([[14, 15]])

In [ ]:
arr[1:4,1:3]

array([[ 7,  8],
       [12, 13]])

In [ ]:
arr[:,3:5]

array([[ 4,  5],
       [ 9, 10],
       [14, 15]])

In [ ]:
arr1=["heelo",1,2,2]


In [ ]:
print(arr1)

['heelo', 1, 2, 2]


In [ ]:
arr1=np.array(arr1)

In [ ]:
print(arr1)

['heelo' '1' '2' '2']


In [ ]:
type(arr1)

numpy.ndarray

<h2> Fancy Indexing<h2>

In [ ]:
arr=np.array([10,20,30,40,50,60])
#Suppose we want to extract elements at 2nd 5th and 0th index
index=[0,2,5]
arr[index]

array([10, 30, 60])

In [ ]:
#Fancy indexing with 2-D arrays
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
#Suppose we want to extract elements at (1,2),(3,3),(2,1),(1,1)
row_indices=[0,2,1,0] #Here we pass the row indices in the list
column_indices=[1,2,0,0] #Here we pass the column indices in the list
arr[row_indices,column_indices]

array([2, 9, 4, 1])

In [ ]:
#Fancy indexing combined with slicing
arr=np.array([[1,2,3],[4,5,6]])
#Suppse we want to extract the elements of 2nd row leaving the middle element
arr[1,[0,2]]

array([4, 6])

<h3>Boolean Masks are a bunch of true , false values wich determines whether a condition is true or not</h3>

In [ ]:
x=np.array([2,5,7,8,9,12,14])
mask=(x%2==0)
print(mask)
print(x[mask])

[ True False False  True False  True  True]
[ 2  8 12 14]


<h1>Slicing<h1>


In [ ]:
#start:stop:step
# 1D
t=np.array([1,2,3,4,5,6])
print(t)
print("2 to 5",t[1:5])
print("2 to end",t[1:])
print("jump 2",t[::2])

[1 2 3 4 5 6]
2 to 5 [2 3 4 5]
2 to end [2 3 4 5 6]
jump 2 [1 3 5]


In [ ]:
# 2D
t=np.array([[1,2,3,4,5],[9,8,7,6,5],[1,2,3,4,5]])
print(t)
print("8 to 5:",t[1,1:])


[[1 2 3 4 5]
 [9 8 7 6 5]
 [1 2 3 4 5]]
8 to 5: [8 7 6 5]


<h1>** Inbuilt Functions**</h1>

In [ ]:
# np.arange(start,stop,step)
arr=np.arange(0,10)

In [ ]:
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
arr=np.arange(0,20,step=3)

In [ ]:
print(arr)

[ 0  3  6  9 12 15 18]


In [ ]:
np.arange(4)

array([0, 1, 2, 3])

In [ ]:
np.arange(-3,3)

array([-3, -2, -1,  0,  1,  2])

In [ ]:
np.arange(-3,4,3)

array([-3,  0,  3])

In [ ]:
np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
# linspace ,def linspace(start, stop, num=), gives a particular space, num specifies how may points we basically want,equally spaced
np.linspace(0,20,num=5, dtype=int)

array([ 0,  5, 10, 15, 20])

In [ ]:
# Copy Function and Broadcasting , creating an another memory space , (to remove the acccess of one variable to another variable)

In [ ]:
arr

array([b'1', b'2', b'3', b'4'], dtype='|S1')

In [ ]:
arr[3:]=100

In [ ]:
print(arr)

[  0   3   6 100 100 100 100]


In [ ]:
arr1=arr

In [ ]:
arr1[3:]=500

In [ ]:
print(arr1)

[  0   3   6 500 500 500 500]


In [ ]:
arr1=arr.copy()

In [ ]:
print(arr)
arr1[3:]=500
print(arr1)

[  0   3   6 100 100 100 100]
[  0   3   6 500 500 500 500]


Some conditions useful in EDA

In [ ]:
arr=np.array([1,1,2,3,4,5])
print(arr)

[1 1 2 3 4 5]


In [ ]:
val=2
arr>2

array([False, False, False,  True,  True,  True])

In [ ]:
arr*2

array([ 2,  2,  4,  6,  8, 10])

In [ ]:
arr-2

array([-1, -1,  0,  1,  2,  3])

In [ ]:
arr

array([  0,   3,   6, 100, 100, 100, 100])

In [ ]:
arr[arr<2]    # getting the elements rather than true or false

array([0])

In [ ]:
# np.ones , it replaces all the elements by 1
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.ones(5,dtype=int)

array([1, 1, 1, 1, 1])

In [ ]:
np.ones((2,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
# np.zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# empty array
np.empty(3)

array([2.e-323, 3.e-323, 4.e-323])

In [ ]:
# eye return daigonals as 1
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
# np.full
np.full((2,2),7)

array([[7, 7],
       [7, 7]])

In [ ]:
e = np.random.random((2,2))
print(e)

[[0.5501246  0.97507242]
 [0.24955954 0.18913805]]


In [ ]:
# Random Distribution ,rand() function , selection is between 0 and 1.
#np.random.rand(3,3) , selects some random values of this given shape
np.random.rand(3,3)

array([[0.82449913, 0.85015228, 0.12687989],
       [0.32148554, 0.7304634 , 0.50061776],
       [0.01742649, 0.84373733, 0.87682642]])

In [ ]:
np.random.rand(2,3)

array([[0.31937134, 0.04631522, 0.23999659],
       [0.01156202, 0.5872366 , 0.60950466]])

In [ ]:
# randn() function returns values close to zero, maybe positive negative
np.random.randn(3)

array([0.11899361, 0.37680677, 0.04452973])

In [ ]:
# ranf() fills with various float numbers in the half open interval [0.0,1.0)
np.random.ranf(2)

array([0.56585595, 0.91651372])

In [ ]:
# randint() genrate random numbers between a range (min,max,total_values)
np.random.randint(5,50,10)

array([36, 34, 32,  5, 27, 41,  5, 11, 16, 12])

In [ ]:
# appending values
arr = np.array([1, 8, 3, 3, 5])
print('Original Array : ', arr)

# appending to the array
arr = np.append(arr, [7])
print('Array after appending : ', arr)

Original Array :  [1 8 3 3 5]
Array after appending :  [1 8 3 3 5 7]


In [ ]:
# swapping the columns
arr1=np.arange(12).reshape(3,4)
print("Origanal Array\n",arr1)
arr1[:,[0,3]]=arr1[:,[3,0]]
print("Swapped Array\n",arr1)


Origanal Array
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Swapped Array
 [[ 3  1  2  0]
 [ 7  5  6  4]
 [11  9 10  8]]


<h1>Arthimetic Operations</h1>

In [ ]:
# one D
a = np.array([14, 23, 32, 41])
b = np.array([5,  4,  3,  2])
print("a + b  =", a + b)
print("a - b  =", a - b)
print("a * b  =", a * b)
print("a / b  =", a / b)
print("a // b  =", a // b)
print("a % b  =", a % b)
print("a ** b =", a ** b)

a + b  = [19 27 35 43]
a - b  = [ 9 19 29 39]
a * b  = [70 92 96 82]
a / b  = [ 2.8         5.75       10.66666667 20.5       ]
a // b  = [ 2  5 10 20]
a % b  = [4 3 2 1]
a ** b = [537824 279841  32768   1681]


In [ ]:
x=np.array([1,2,3,4,5])
add=x+3
sub=x-3
mul=x*3
print(add)
print(sub)
print(mul)

[4 5 6 7 8]
[-2 -1  0  1  2]
[ 3  6  9 12 15]


In [ ]:
p=np.array([1,2,3,4,5])
q=np.array([1,2,3,4,5])
print(np.add(p,q))
print(np.subtract(p,q))
print(np.power(p,q))

[ 2  4  6  8 10]
[0 0 0 0 0]
[   1    4   27  256 3125]


In [ ]:
# 2D arrays
x_2d=np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(x_2d)
y_2d=np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(y_2d)
xy_add=x_2d+y_2d
print(xy_add)

[[1 2 3 4 5]
 [1 2 3 4 5]]
[[1 2 3 4 5]
 [1 2 3 4 5]]
[[ 2  4  6  8 10]
 [ 2  4  6  8 10]]


<h1>Arthimetic Functions<h1>


In [ ]:
# min
x=np.array([1,2,3,4,58,6])
print(np.min(x))

1


In [ ]:
# max
x=np.array([1,2,3,4,58,6])
print(np.max(x))


58


In [ ]:
# argmin gives the position of min,max
x=np.array([1,2,3,4,58,6])
print(np.min(x),np.argmin(x))
print(np.max(x),np.argmax(x))

1 0
58 4


In [ ]:
# getting min, max of 2D
x=np.array([[1,2,3,4],[5,7,8,9]])
print("columns")
print("min",np.min(x,axis=0))          # axis 0 =column
print("max",np.max(x,axis=0))
print("rows")
print("min",np.min(x,axis=1))          # axis 1 =row
print("min",np.max(x,axis=1))


columns
min [1 2 3 4]
max [5 7 8 9]
rows
min [1 5]
min [4 9]


In [ ]:
# squareroot
p=np.array([1,2,3,4,5])
print("sqrt:",np.sqrt(p))


sqrt: [1.         1.41421356 1.73205081 2.         2.23606798]


In [ ]:
var2= np.array([4,5,6])
print(np.sin(var2))
print(np.cos(var2))

[-0.7568025  -0.95892427 -0.2794155 ]
[-0.65364362  0.28366219  0.96017029]


In [ ]:
# cumulative sum [1,2,3,4]=1,1+2,3+3,6+4
var2= np.array([1,2,3,4])
print(np.cumsum(var2))

[ 1  3  6 10]


In [ ]:
# sum
p=np.array([1,2,3,4,5])
print(np.sum(p))


15


<h3> Numpy Arrays Functions</h3>

In [ ]:
# Search Array, search an array for a certain value, and return the indexes that get a match, uses where()
var3=np.array([1,3,2,4,5,2,7,9,6,8,7,])
p=np.where( var3==2)
print(p)

(array([2, 5]),)


In [ ]:
var=np.array([1,3,2,4,5,2,7,9,6,8,7,])
p=np.where(var%2==0)
print(p)

(array([2, 3, 5, 8, 9]),)


<h3> Search Sorted Array</h3>
<p> performs a binary search in the array and returns the index where the specified value would be inserted to maintain the search order</p>

In [ ]:
#search sort function
f=np.array([1,2,3,4,6,7])
x1=np.searchsorted( f, 5)
print(x1)

4


In [ ]:
f1=np.array([1,2,3,4,9,10])
x2=np.searchsorted(f1,[5,6,7,8],side="right")
print(x2)


[4 4 4 4]


Sorted Arrays: ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or descending

In [ ]:
# sort function
x3=np.array([9,4,5,1,7,2,6,3])
x=np.sort(x3)
print(x)

[1 2 3 4 5 6 7 9]


In [ ]:
a=np.array(["t","w","z","a","x"])
a1=np.sort(a)
print(a1)

['a' 't' 'w' 'x' 'z']


In [ ]:
a2=np.array([[4,2,3],[9,5,7],[10,5,3]])
z=np.sort(a2)
print(z)

[[ 2  3  4]
 [ 5  7  9]
 [ 3  5 10]]


**Filter Array**  getting some elements out of an existing array and creating  new array out of them

In [ ]:
a=np.array(["t","w","z","a","x"])
f=[True,True,False,True,False]
new_a=a[f]
print(new_a)

['t' 'w' 'a']


**Insert **

In [ ]:
d=np.array([1,2,3,4,5])
print(d)
print(type(d))
np.insert(d,2,10)          #(arrayname,position,value)

[1 2 3 4 5]
<class 'numpy.ndarray'>


array([ 1,  2, 10,  3,  4,  5])

In [ ]:
np.insert(d,(2,4),10)

array([ 1,  2, 10,  3,  4, 10,  5])

In [ ]:
d1=np.array([[4,2,3],[9,5,7],[10,5,3]])
print(d1)
v=np.insert(d1,2,6,axis=0)

print(v)

[[ 4  2  3]
 [ 9  5  7]
 [10  5  3]]
[[ 4  2  6  3]
 [ 9  5  6  7]
 [10  5  6  3]]


**Delete**

In [ ]:
d=np.array([1,2,3,4,5])
print(d)
np.delete(d,2)

[1 2 3 4 5]


array([1, 2, 4, 5])

<h1> Broadcasting <h1>
**rules for broadcasting**

NumPy compares sets of array dimensions from right to left
(x,y) and(m,n) the dimensions of two arrays

*   if x=y and y=n operation will take place
*   if x=1 and y=n operation will take place

*   if y=1 and x=m operation will take place
*   if x=1 and y!=n operation will not take place

*   if x=1 and n=1 then y==m opearion to tkae place
*   if x=1 and y=1 then no matter what operation will take place

Broadcastable shapes:

*
(10, 5) and (10, 1),
(10, 5) and (5, )

Shapes which are not broadcastable:

*
(10, 5) and (5, 10),
(10, 5) and (10, )







In [ ]:
#scenario 1  dimensions are same operation is possible
x1=np.arange(0,10).reshape(5,2)
x2=np.arange(10,20).reshape(5,2)
print(x1)
print("\n",x2)
x1+x2

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]

 [[10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


array([[10, 12],
       [14, 16],
       [18, 20],
       [22, 24],
       [26, 28]])

In [ ]:
# Scenario 2 dimensions are different
var=np.arange(9).reshape(3,3)
var1=np.arange(3).reshape(1,3)             # here comes the concept of broadcasting addition will be still possible
print(var,"\n \n   ",var1)


[[0 1 2]
 [3 4 5]
 [6 7 8]] 
 
    [[0 1 2]]


In [ ]:
print(var+var1)

[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]]


Concatenating in Arrays

In [ ]:
# concatenating rows, np.concatenate() concatenates along the first axis by default
classroom_ids_and_sizes = np.array([[1, 22], [2, 21], [3, 27], [4, 26]])
print(classroom_ids_and_sizes)
new_classrooms = np.array([[5, 30], [5, 17]])
print("\n",new_classrooms)
print("after cocatenation")
np.concatenate((classroom_ids_and_sizes, new_classrooms))

[[ 1 22]
 [ 2 21]
 [ 3 27]
 [ 4 26]]

 [[ 5 30]
 [ 5 17]]
after cocatenation


array([[ 1, 22],
       [ 2, 21],
       [ 3, 27],
       [ 4, 26],
       [ 5, 30],
       [ 5, 17]])

In [ ]:
#Concatenating columns
classroom_ids_and_sizes = np.array([[1, 22], [2, 21], [3, 27], [4, 26]])
grade_levels_and_teachers = np.array([[1, "James"], [1, "George"], [3,"Amy"],
[3, "Meehir"]])
np.concatenate((classroom_ids_and_sizes, grade_levels_and_teachers), axis=1)

array([['1', '22', '1', 'James'],
       ['2', '21', '1', 'George'],
       ['3', '27', '3', 'Amy'],
       ['4', '26', '3', 'Meehir']], dtype='<U21')